package knowledge

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// DistillProjectLearnings aggregates all feature learnings into the global project learnings
func DistillProjectLearnings(root string) error {
	featuresDir := filepath.Join(root, ".specs", "features")
	entries, err := os.ReadDir(featuresDir)
	if err != nil {
		return err
	}

	var globalLearnings strings.Builder
	globalLearnings.WriteString("# Global Project Learnings\n\n")
	globalLearnings.WriteString("Autogenerated by hb distill\n\n")

	for _, entry := range entries {
		if entry.IsDir() {
			learningsPath := filepath.Join(featuresDir, entry.Name(), "LEARNINGS.md")
			content, err := os.ReadFile(learningsPath)
			if err == nil {
				globalLearnings.WriteString(fmt.Sprintf("## Feature: %s\n", entry.Name()))
				globalLearnings.WriteString(string(content))
				globalLearnings.WriteString("\n\n---\n")
			}
		}
	}

	outputPath := filepath.Join(root, ".specs", "project", "LEARNINGS.md")
	return os.WriteFile(outputPath, []byte(globalLearnings.String()), 0644)
}
