package rules

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// CompileRules aggregates all global mandates and feature rules into .cursorrules
func CompileRules(root string) error {
	globalMandatesPath := filepath.Join(root, ".specs", "codebase", "GLOBAL_MANDATES.md")
	globalContent, _ := os.ReadFile(globalMandatesPath)

	var output strings.Builder
	output.WriteString("# Generated by hb sync --rules\n\n")
	output.WriteString("## Global Mandates\n")
	output.WriteString(string(globalContent))
	output.WriteString("\n\n## Feature Rules\n")

	featuresDir := filepath.Join(root, ".specs", "features")
	entries, _ := os.ReadDir(featuresDir)

	for _, entry := range entries {
		if entry.IsDir() {
			specPath := filepath.Join(featuresDir, entry.Name(), "spec.md")
			specContent, err := os.ReadFile(specPath)
			if err == nil {
				output.WriteString(fmt.Sprintf("\n### %s\n", entry.Name()))
				// Extract goals/criteria
				output.WriteString(string(specContent))
			}
		}
	}

	cursorRulesPath := filepath.Join(root, ".cursorrules")
	return os.WriteFile(cursorRulesPath, []byte(output.String()), 0644)
}
