package rules

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/klebersonromero/hb/internal/scanner"
)

// Generate compila mandatos e skills no arquivo .cursorrules e distribui para pastas de agentes
func Generate(root string, targetSkills []string) error {
	var cursorBuilder strings.Builder
	cursorBuilder.WriteString("# Cursor Rules - AI Agent Skills Hub\n")
	cursorBuilder.WriteString("> This file is auto-generated by the Skills Hub compiler.\n\n")

	// Pastas de destino dos agentes
	agentFolders := []string{".gemini/rules", ".claude/rules", ".agent/rules"}
	for _, folder := range agentFolders {
		os.MkdirAll(filepath.Join(root, folder), 0755)
	}

	// 1. Processar Mandatos Globais
	mandatesPath := filepath.Join(root, ".specs", "codebase", "GLOBAL_MANDATES.md")
	mandates, err := os.ReadFile(mandatesPath)
	if err == nil {
		// Adicionar ao .cursorrules
		cursorBuilder.Write(mandates)
		cursorBuilder.WriteString("\n---\n\n")

		// Distribuir para agentes
		for _, folder := range agentFolders {
			target := filepath.Join(root, folder, "global-mandates.md")
			os.WriteFile(target, mandates, 0644)
		}
	}

	// 2. Coletar Skills
	allSkills, err := scanner.FindSkills(root)
	if err != nil {
		return err
	}

	skillMap := make(map[string]string)
	for _, s := range allSkills {
		skillMap[filepath.Base(s.Path)] = filepath.Join(s.Path, "SKILL.md")
	}

	// Determinar quais skills incluir
	var toIncludeNames []string
	if len(targetSkills) > 0 {
		for _, name := range targetSkills {
			if _, exists := skillMap[name]; exists {
				toIncludeNames = append(toIncludeNames, name)
			}
		}
	} else {
		for name := range skillMap {
			toIncludeNames = append(toIncludeNames, name)
		}
		sort.Strings(toIncludeNames)
	}

	// 3. Processar e Distribuir Skills
	for _, skillName := range toIncludeNames {
		path := skillMap[skillName]
		content, err := os.ReadFile(path)
		if err == nil {
			// Adicionar ao .cursorrules
			cursorBuilder.WriteString(fmt.Sprintf("## SKILL: %s\n\n", strings.ToUpper(skillName)))
			cursorBuilder.Write(content)
			cursorBuilder.WriteString("\n---\n\n")

			// Distribuir para agentes (nome em minúsculo + .md)
			fileName := strings.ToLower(skillName) + ".md"
			for _, folder := range agentFolders {
				target := filepath.Join(root, folder, fileName)
				os.WriteFile(target, content, 0644)
			}
		}
	}

	// Salvar .cursorrules legada
	cursorPath := filepath.Join(root, ".cursorrules")
	return os.WriteFile(cursorPath, []byte(cursorBuilder.String()), 0644)
}
