import os
import argparse
from pathlib import Path

def generate_cursorrules(skills):
    root_dir = Path(__file__).parent.parent
    output_file = root_dir / ".cursorrules"
    
    mandates_path = root_dir / ".specs" / "codebase" / "GLOBAL_MANDATES.md"
    
    content = ["# Cursor Rules - AI Agent Skills Hub\n"]
    content.append("> This file is auto-generated by the Skills Hub compiler.\n\n")
    
    if mandates_path.exists():
        content.append("## GLOBAL MANDATES\n")
        content.append(mandates_path.read_text(encoding="utf-8"))
        content.append("\n---\n")
    else:
        print(f"Warning: Global mandates not found at {mandates_path}")
    
    if not skills:
        content.append("> Note: No specific skills were injected. To inject skills into Cursor context, run:\n")
        content.append("> `uv run python scripts/generate_cursorrules.py --skills sdd,python-uv,fastapi-expert`\n")
    else:
        for skill in skills:
            skill_path = root_dir / skill / "SKILL.md"
            if skill_path.exists():
                content.append(f"## SKILL: {skill.upper()}\n")
                content.append(skill_path.read_text(encoding="utf-8"))
                content.append("\n---\n")
            else:
                print(f"Warning: Skill '{skill}' not found.")
                
    output_file.write_text("\n".join(content), encoding="utf-8")
    print(f"Successfully generated .cursorrules with skills: {', '.join(skills) if skills else 'None (Base Mandates Only)'}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate .cursorrules with specific skills.")
    parser.add_argument("--skills", type=str, help="Comma-separated list of skills to include", default="")
    args = parser.parse_args()
    
    skills_list = [s.strip() for s in args.skills.split(",")] if args.skills else []
    generate_cursorrules(skills_list)
