import os
import argparse
from pathlib import Path

def generate_cursorrules(skills):
    root_dir = Path(__file__).parent.parent
    output_file = root_dir / ".cursorrules"
    
    mandates_path = root_dir / ".specs" / "codebase" / "GLOBAL_MANDATES.md"
    
    content = ["# Cursor Rules - AI Agent Skills Hub\n"]
    content.append("> This file is auto-generated by the Skills Hub compiler.\n\n")
    
    # 1. Injetar Global Mandates (Bootstrap + Router + Mandates + Exit Gate)
    if mandates_path.exists():
        content.append(mandates_path.read_text(encoding="utf-8"))
        content.append("\n---\n")
    else:
        print(f"Warning: Global mandates not found at {mandates_path}")
    
    # 2. Injetar Skills (Compactadas)
    if not skills:
        # Se não passar skills, vamos pegar TODAS as que existem para garantir visibilidade
        skills = [d.name for d in root_dir.iterdir() if d.is_dir() and (d / "SKILL.md").exists()]
        print(f"No specific skills provided. Including all {len(skills)} found skills.")

    for skill in sorted(skills):
        skill_path = root_dir / skill / "SKILL.md"
        if skill_path.exists():
            content.append(f"## SKILL: {skill.upper()}\n")
            content.append(skill_path.read_text(encoding="utf-8"))
            content.append("\n---\n")
        else:
            print(f"Warning: Skill '{skill}' not found.")
                
    output_file.write_text("\n".join(content), encoding="utf-8")
    print(f"Successfully generated .cursorrules with {len(skills)} skills and Mandatory Hooks.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate .cursorrules with specific skills.")
    parser.add_argument("--skills", type=str, help="Comma-separated list of skills to include", default="")
    args = parser.parse_args()
    
    skills_list = [s.strip() for s in args.skills.split(",")] if args.skills else []
    generate_cursorrules(skills_list)
