name: HB CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build HB CLI
      run: go build -v -o hb main.go
      working-directory: ./hb

    - name: Run HB Audit
      run: ./hb/hb sdd audit
    
    - name: Run Unit Tests
      run: go test -v ./...
      working-directory: ./hb
